### ISSUE TITLE
Cannot build with hspec 2.0.1

### ISSUE THREAD

**Issue by ocharles** [mitchellwrosen/tasty-hspec#3]
After increasing upper bounds:

```
building
Building tasty-hspec-0.2...
Preprocessing library tasty-hspec-0.2...
[1 of 1] Compiling Test.Tasty.Hspec ( Test/Tasty/Hspec.hs, dist/build/Test/Tasty/Hspec.o )

Test/Tasty/Hspec.hs:47:22:
    Not in scope: data constructor ‘H.SpecGroup’

Test/Tasty/Hspec.hs:48:22:
    Not in scope: data constructor ‘H.BuildSpecs’

Test/Tasty/Hspec.hs:49:22:
    Not in scope: data constructor ‘H.SpecItem’
```
